[build]
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[build.processing]
  skip_processing = false
[build.processing.css]
  minify = true
[build.processing.js]
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
