[build]
  command = "next build"
  publish = ".next/standalone"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [
    ".next/standalone/**",
    ".next/static/**"
  ]
  node_bundler = "esbuild"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000,
    immutable
    '''

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image"
  to = "/.netlify/functions/next-image"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/.netlify/functions/next-server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next-server"
  status = 200
  force = true

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
